=== Kabegami/MLBDA/tme5/dtd/restaurant2.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT restaurant (nom, lieu, fermeture, etoile, menus)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT fermeture (#PCDATA)>
<!ELEMENT etoile (#PCDATA)>
<!ELEMENT menus (menu+)>
<!ELEMENT tarif (#PCDATA)>
<!ELEMENT menu (nom,tarif)>
<!ELEMENT lieu (#PCDATA)>

=== Kabegami/MLBDA/tme5/dtd/restaurant2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE restaurant SYSTEM "restaurant2.dtd">

<restaurant>
  <nom> CROUS </nom>
  <lieu> Paris</lieu>
  <fermeture> weekend </fermeture>
  <etoile> quedal </etoile>
  <menus>
    <menu> <nom>menu pour les pauvres</nom>
    <tarif> 2 euros </tarif>
    </menu>
  </menus>
</restaurant>
